#!/bin/bash
# configure-wifi
#
# Copyright 2018, F123 Consulting, <information@f123.org>
# Copyright 2018, Kyle, <kyle@free2.ml>
# Copyright 2018, Storm Dragon, <storm_dragon@linux-a11y.org>
#
# This is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3, or (at your option) any later
# version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this package; see the file COPYING.  If not, write to the Free
# Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.
#
#--code--

# Some useful settings and functions needed in this configurator

export WORK_DIR=`dirname $0`
# Setup for gettext localization
export TEXTDOMAIN=configure-wifi
export TEXTDOMAINDIR=/usr/share/locale
. gettext.sh

passwordbox() {
    # Returns: text entered by the user
    # Args 1, Instructions for box.
    # args: 2 initial text (optional)
    rofi -p "$1"  -dmenu -l 0 -password
}

msgbox() {
# Returns: None
# Shows the provided message on the screen with an ok button.
  rofi -e "$*"
}

menulist() {
  for line in "$@" ;do
    echo $line
  done | rofi -dmenu -l 10 | cut -d' ' -f1
}

declare -A network_map
network_id=0
get_network_map() {
  declare -A keys
  for i in Quality ESSID "Encryption key";do
    keys["$i"]=1
  done

  ifs="$IFS"
  IFS=$'\n'
  for line in $(iwlist wlan0 scan ); do
    line=`echo $line | grep -o '[^ ].*:*'`
    is_quality=`echo $line | grep -c 'Quality='`
    if [[ $is_quality == 1 ]];then
      key=`echo $line | cut -d'=' -f1 | sed 's/ //g'`
      value=`echo $line | cut -d'=' -f2 | cut -d'/' -f1 `
    else
      key=`echo $line | cut -d':' -f1 `
      value=`echo $line | cut -d':' -f2- | cut -d'"' -f2`
    fi
    if [[ ${keys["$key"]} == 1 ]] ;then
      network_map["$network_id#$key"]=$value
      if [[ ${key} == "ESSID" ]] ; then
        ESSID=`echo -e $value`
        network_map["$network_id#$key"]=${ESSID}
        network_id=`expr $network_id + 1`
      fi
    fi
  done
  IFS="$ifs"
  network_id=`expr ${network_id} - 1`
}

networks=()
get_networks() {

  network_quality=()
  for i in `seq 0 ${network_id}`;do
      quality=${network_map["$i#Quality"]}
      network_quality+=("$i,${quality}")
  done

  IFS=$'\n' sorted=($(sort -r -t',' -k2 <<<"${network_quality[*]}"))
  unset IFS

  for key in "${!sorted[@]}";do
    wifi_id=`echo ${sorted["$key"]} | cut -d',' -f1`
    essid=${network_map["$wifi_id#ESSID"]}
    quality=${network_map["$wifi_id#Quality"]}
    networks+=("$wifi_id ${essid} ${quality}")
    # networks+=("$wifi_id")
    # networks+=("${essid} ${quality}")
  done
}

make_cfg() {
if test -z $pass; then
	cat > ${WPA_CFG_FILE} <<-endOfFile
		network={
		    ssid="$network"
		    key_mgmt="NONE"
		}
	endOfFile
else
	wpa_passphrase "$network" "$pass" | grep -v \#psk > ${WPA_CFG_FILE}
fi
}

# Be sure the wireless interface is up.
ip link set up dev wlan0

# Scan for available wifi networks and store them in an array.

source ./networks.data

# Present the available networks in a selectable menu, only if networks can be found
if test -z "$networks"; then
	msgbox "$(gettext "Unable to get a list of networks. Either you have no wireless networks in range or there is a problem with your wireless adapter.")"
	exit 0
else

  n_id="$(menulist "${networks[@]}")"
  network=${network_map["$n_id#ESSID"]}
fi
test -z "$network" && exit 0

is_encrypted=${network_map["$n_id#Encryption key"]}

# Configure wpa_supplicant
mkdir -p ${WORK_DIR}/wpa_supplicant
WPA_CFG_FILE=${WORK_DIR}/wpa_supplicant/`echo ${network} | md5sum | cut -d' ' -f1`.conf
echo $WPA_CFG_FILE

if [[ $is_encrypted == "off" ]]; then
  iwconfig wlan0 essid "$network"
# Combine the network ESSID and password to add a Network section to the wpa_supplicant configuration file with an encrypted password,
# or if no password is specified, add a Network section with no key management.
else
  if [[ ! -r ${WPA_CFG_FILE} ]] ; then
      pass="$(passwordbox "$(eval_gettext "Enter the password for \${network}.
Just press the enter key if \$network is unsecured.")")" || exit 0
      make_cfg ${WPA_CFG_FILE}
  fi

  killall wpa_supplicant
  wpa_supplicant -i wlan0 -c ${WPA_CFG_FILE} -B

fi

for testconn in {1..5}; do
  iface=wlan0
  udhcp_pidfile=/run/udhcpc.${iface}.pid
  if test -f ${udhcp_pidfile}; then
    kill -USR2 $(/bin/cat ${udhcp_pidfile}); 
    kill -TERM $(/bin/cat ${udhcp_pidfile}); 
  fi
  udhcpc -p ${udhcp_pidfile} -i wlan0

  gw=$(ip route get 8.8.8.8 | head -n1 | cut -d' ' -f3)
	ping -c1 $gw >& /dev/null && connected=1 && break
	sleep 1
done

# Detect a connection. Timeout after 10 seconds if the connection is not detected.
test $connected && msgbox "$(gettext "Your wireless network connection has been configured and is now working.")" ||msgbox "$(gettext "There was a problem configuring the wireless network. Be sure you selected the correct network, and that your password is correct.")"
